FROM apache/airflow:2.9.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements_airflow.txt requirements_airflow.txt
RUN pip install --no-cache-dir -r requirements_airflow.txt